import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.scss"


export const metadata: Metadata = {
  title: "Frontend App Pizzaria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        {/* <h1>header</h1> */}
        {children}
      </body>
    </html>
  );
}
