import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.scss"
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Frontend App Pizzaria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        {/* <h1>header</h1> */}
        <Toaster 
          position="bottom-right"
          toastOptions={{
            style:{
              backgroundColor: "#f1f1f1",
              color: "#131313",
              borderColor: "rgba(255,255,255,0.5)"
            }
          }}
        />
        {children}
      </body>
    </html>
  );
}
